version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=darkhumor
    restart: always  # Add restart policy for MongoDB as well

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=darkhumor
      - ME_CONFIG_MONGODB_SERVER=mongodb  # Ensure this matches the MongoDB service name
   
    depends_on:
      - mongodb  # Ensure this matches the MongoDB service name
      #j